name: "Inspektre Scan"
on: push
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze code
        uses: actions/checkout@v2
        uses: georgismitev/deepcode-code-scanning-analysis@master
        env:
          DEEPCODE_TOKEN: ${{secrets.DEEPCODE_TOKEN}}
        uses: inspektre/codeintel-gh@v1
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install Inspektre
        env:
          NPM_CONFIG_PREFIX: "~/.npm-global"
        run: |
          export PATH="$(yarn global bin):$PATH"
          yarn global add @inspektre/inspektre
      - name: Inspect results
        env:
          INSPEKTRE_TOKEN: ${{secrets.INSPEKTRE_TOKEN}}
          INSPEKTRE_CLIENT_ID: ${{secrets.INSPEKTRE_CLIENT_ID}}
          INSPEKTRE_CLIENT_SECRET: ${{secrets.INSPEKTRE_CLIENT_SECRET}}
        run: |
          ~/.npm-global/bin/inspektre reauthorize
          ~/.npm-global/bin/inspektre inspect -f ${{GITHUB_WORKSPACE}}/AppInspectorResults.json --sarif output.sarif --deepcode
