name: A DeepCode analysis

on:
  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  Deepcode-Build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Perform DeepCode analysis
      uses: georgismitev/deepcode-code-scanning-analysis@master
      env:
        DEEPCODE_TOKEN: ${{secrets.DEEPCODE_TOKEN}}

    - name: Upload report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: output.sarif
